# Generated by Django 5.2.1 on 2025-05-27 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoCoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_name', models.CharField(max_length=15)),
                ('coin_symbol', models.CharField(max_length=5)),
                ('coin_price', models.PositiveIntegerField()),
                ('coin_count', models.PositiveIntegerField()),
            ],
        ),
    ]
