# Generated by Django 5.2.1 on 2025-05-30 09:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptocoin',
            name='add_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
